# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editentrywindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_edit_entry_window(object):
    def setupUi(self, edit_entry_window):
        edit_entry_window.setObjectName("edit_entry_window")
        edit_entry_window.resize(800, 600)
        edit_entry_window.setStyleSheet("color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(edit_entry_window)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 40, 211, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 211, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 160, 211, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 220, 111, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(20, 60, 151, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 120, 151, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(20, 180, 151, 22))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 240, 81, 26))
        self.pushButton.setObjectName("pushButton")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(160, 10, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        edit_entry_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(edit_entry_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        edit_entry_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(edit_entry_window)
        self.statusbar.setObjectName("statusbar")
        edit_entry_window.setStatusBar(self.statusbar)
        self.actionClose = QtWidgets.QAction(edit_entry_window)
        self.actionClose.setObjectName("actionClose")
        self.menuFile.addAction(self.actionClose)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(edit_entry_window)
        QtCore.QMetaObject.connectSlotsByName(edit_entry_window)

    def retranslateUi(self, edit_entry_window):
        _translate = QtCore.QCoreApplication.translate
        edit_entry_window.setWindowTitle(_translate("edit_entry_window", "MainWindow"))
        self.label.setText(_translate("edit_entry_window", "Enter event ID for desired edit:"))
        self.label_2.setText(_translate("edit_entry_window", "Enter ranger ID:"))
        self.label_3.setText(_translate("edit_entry_window", "Enter new classification:"))
        self.label_4.setText(_translate("edit_entry_window", "Confirm changes: "))
        self.pushButton.setText(_translate("edit_entry_window", "Enter"))
        self.label_5.setText(_translate("edit_entry_window", "Edit entry"))
        self.menuFile.setTitle(_translate("edit_entry_window", "File"))
        self.actionClose.setText(_translate("edit_entry_window", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    edit_entry_window = QtWidgets.QMainWindow()
    ui = Ui_edit_entry_window()
    ui.setupUi(edit_entry_window)
    edit_entry_window.show()
    sys.exit(app.exec_())
